#!/usr/bin/env bash
# reproduce_paper.sh
# One-command reproduction of the BGF paper results.
#
# Usage:
#   bash reproduce_paper.sh            # fast sanity check (CPU, ~5 min)
#   bash reproduce_paper.sh --full     # full paper run (CPU baselines, ~30 min)
#   bash reproduce_paper.sh --figures  # regenerate all figures from existing experiments
#
# GPU-dependent LLM experiments (--include-llm) are excluded from automatic
# reproduction; run them manually via the pipeline scripts listed at the bottom
# of this file.
#
# ── Figure / Table manifest ──────────────────────────────────────────────────
# Table 1  (Ablation ladder V0-V4)
#   Generated by: python scripts/run_full_pipeline.py
#   Output:       analysis/tables/ablation_results.csv
#
# Table 2  (Cross-model bias index)
#   Generated by: python scripts/run_cross_model.py
#   Output:       analysis/tables/cross_model_results.csv
#
# Table 3  (Statistical significance: Mann-Whitney, Cohen's d)
#   Generated by: python scripts/run_full_pipeline.py (--seeds flag)
#   Output:       analysis/tables/significance_tests.csv
#
# Table 4  (Cross-cultural Spearman ρ)
#   Generated by: python scripts/run_cross_cultural.py
#   Output:       analysis/tables/cross_cultural_correlation.csv
#
# Figure 1 (Cooperation rate trajectories, multi-seed CI)
#   Generated by: python scripts/plot_trajectories_full.py --seeds 5
#   Output:       analysis/figures/cooperation_trajectories.pdf
#
# Figure 2 (Gini coefficient trajectories)
#   Generated by: python scripts/plot_trajectories_full.py --seeds 5
#   Output:       analysis/figures/gini_trajectories.pdf
#
# Figure 3 (Cross-model bias comparison bar chart)
#   Generated by: python scripts/plot_cross_model_comparison.py
#   Output:       analysis/figures/cross_model_bias_comparison.pdf
#
# Figure 4 (Cross-cultural scatter: ESS trust vs simulated cooperation)
#   Generated by: python scripts/plot_cross_cultural_validation.py
#   Output:       analysis/figures/cross_cultural_validation.pdf
#
# Figure 5 (Phase transitions: cooperation collapse, Gini, topology, power law)
#   Generated by: python scripts/plot_phase_transitions.py
#   Output:       analysis/figures/phase_transitions.pdf
#
# ── GPU experiment pipelines (manual, require 16 GB VRAM) ───────────────────
# bash pipeline_phase_c.sh          # 100 agents, 100 rounds, LLM + RAG
# bash pipeline_cross_cultural.sh --include-llm   # cross-cultural LLM run
# bash pipeline_bad_apple.sh        # adversarial agent stress test
# bash pipeline_macro_shock.sh      # macro-economic shock (50% wealth hit)
# bash pipeline_topology.sh         # network topology sweep
# bash pipeline_phase_d.sh          # 500-agent large-scale run
# ────────────────────────────────────────────────────────────────────────────

set -euo pipefail

FULL=0
FIGURES_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --full)    FULL=1 ;;
        --figures) FIGURES_ONLY=1 ;;
    esac
done

echo "======================================================="
echo "  Behavioral Grounding Framework — Paper Reproduction"
echo "======================================================="
echo ""

# ── 1. Python version check ────────────────────────────────────────────────
REQUIRED_PYTHON="3.10"
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "[check] Python version: $PYTHON_VERSION (required >= $REQUIRED_PYTHON)"

python3 -c "
import sys
if (sys.version_info.major, sys.version_info.minor) < (3, 10):
    print('ERROR: Python >= 3.10 is required')
    sys.exit(1)
"

# ── 2. Check / create virtualenv ──────────────────────────────────────────
echo ""
echo "[env]   Checking virtual environment..."
if [[ -d venv ]]; then
    source venv/bin/activate
    echo "        Activated existing venv/."
else
    python3 -m venv venv
    source venv/bin/activate
    pip install --quiet --upgrade pip
    pip install --quiet -r requirements.txt
    echo "        Created venv/ and installed dependencies."
fi

# ── 3. Run test suite ─────────────────────────────────────────────────────
echo ""
echo "[test]  Running test suite..."
pytest tests/ -q --tb=short 2>&1 | tail -10
echo "        Tests passed."

if [[ $FIGURES_ONLY -eq 1 ]]; then
    echo ""
    echo "[fig]   Regenerating all figures from existing experiments..."
    python scripts/run_full_pipeline.py --plots-only
    python scripts/plot_trajectories_full.py --seeds 5 || true
    python scripts/plot_cross_model_comparison.py || true
    python scripts/plot_cross_cultural_validation.py || true
    python scripts/plot_phase_transitions.py || true
    python scripts/export_figures_hires.py || true
    echo ""
    echo "======================================================="
    echo "  Figures regenerated."
    echo "  Output: analysis/figures/"
    echo "======================================================="
    exit 0
fi

# ── 4. Run CPU-only simulation pipeline ──────────────────────────────────
echo ""
if [[ $FULL -eq 1 ]]; then
    echo "[sim]   Running FULL baseline pipeline (30 rounds, 100 agents, seeds 42,123,7)..."
    echo "        → Table 1, Figures 1-2"
    python scripts/run_full_pipeline.py \
        --rounds 30 \
        --agents 100 \
        --seeds 42,123,7
else
    echo "[sim]   Running FAST baseline pipeline (5 rounds, 20 agents, seeds 42,123,7)..."
    echo "        (Use --full for complete paper reproduction)"
    python scripts/run_full_pipeline.py \
        --rounds 5 \
        --agents 20 \
        --seeds 42,123,7
fi

# ── 5. Trust gradient validation (GPU-free) ──────────────────────────────
echo ""
echo "[val]   Running trust-gradient sub-population validation..."
echo "        → Table 3 (partial)"
python scripts/run_trust_gradient.py || echo "        Skipped — run after full LLM experiments."

# ── 6. Cross-cultural validation (CPU baselines) ─────────────────────────
echo ""
echo "[xcult] Running cross-cultural baseline validation..."
echo "        → Table 4"
python scripts/run_cross_cultural.py --policy random || \
    echo "        Skipped — run pipeline_cross_cultural.sh for LLM results."

# ── 7. Regenerate figures ─────────────────────────────────────────────────
echo ""
echo "[fig]   Regenerating figures..."
python scripts/run_full_pipeline.py --plots-only || true
python scripts/plot_trajectories_full.py --seeds 3 || true
python scripts/plot_phase_transitions.py || true
python scripts/export_figures_hires.py || true

echo ""
echo "======================================================="
echo "  Reproduction complete."
echo ""
echo "  Figures:     analysis/figures/"
echo "  Tables:      analysis/tables/"
echo "  Experiments: experiments/"
echo ""
echo "  GPU experiments (LLM policy) must be run separately:"
echo "    bash pipeline_phase_c.sh"
echo "    bash pipeline_cross_cultural.sh --include-llm"
echo "======================================================="
