"""Bootstrap-CI + effect-size report across mx_{A,B,D} seed sweeps.

Reads experiments/mx_{A,B,D}_s{1..N}/summary.json, aggregates the headline
metrics (BRM, Gini, cooperation rate, mean wealth) across seeds, and emits:
  - analysis/tables/bootstrap_ci.csv          per-condition value ± 95% CI
  - analysis/tables/pairwise_effects.csv      Cohen's d + Mann-Whitney U + BH-adj p
  - analysis/tables/bootstrap_ci_report.md    markdown ready to paste into paper

Usage:
    python scripts/bootstrap_ci_report.py
"""

from __future__ import annotations

import json
from itertools import combinations
from pathlib import Path

import numpy as np

from metrics.statistical_inference import (
    benjamini_hochberg,
    bootstrap_ci,
    cohens_d,
    mann_whitney_u,
)

ROOT = Path(__file__).resolve().parent.parent
EXP = ROOT / "experiments"
OUT_DIR = ROOT / "analysis" / "tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)

CONDITIONS = ["A", "B", "D"]
METRICS = [
    ("brm", "metrics.brm"),
    ("gini", "metrics.gini"),
    ("cooperation_rate", "metrics.cooperation_rate"),
    ("mean_wealth", "metrics.mean_wealth"),
    ("jsd_component", "metrics.brm_components.jsd_component"),
    ("stability_component", "metrics.brm_components.stability_component"),
]


def _dig(d: dict, dotted: str):
    cur = d
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur


def collect() -> dict[str, dict[str, list[float]]]:
    """Returns {condition: {metric_name: [values across seeds]}}."""
    data: dict[str, dict[str, list[float]]] = {c: {m: [] for m, _ in METRICS} for c in CONDITIONS}
    for cond in CONDITIONS:
        for path in sorted(EXP.glob(f"mx_{cond}_s*/summary.json")):
            s = json.loads(path.read_text())
            for name, dotted in METRICS:
                v = _dig(s, dotted)
                if v is not None:
                    data[cond][name].append(float(v))
    return data


def main() -> None:
    data = collect()

    # ── Table 1: per-condition value ± 95% CI ─────────────────────────────
    rows = ["condition,metric,n,mean,ci_low,ci_high,std"]
    for cond in CONDITIONS:
        for name, _ in METRICS:
            vals = data[cond][name]
            if not vals:
                continue
            mean = float(np.mean(vals))
            std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
            if len(vals) >= 3:
                _, lo, hi = bootstrap_ci(vals, n_bootstrap=5000, confidence=0.95, random_state=42)
            else:
                lo, hi = mean, mean
            rows.append(f"{cond},{name},{len(vals)},{mean:.6f},{lo:.6f},{hi:.6f},{std:.6f}")
    (OUT_DIR / "bootstrap_ci.csv").write_text("\n".join(rows) + "\n")

    # ── Table 2: pairwise effect sizes + BH-adjusted p-values ─────────────
    pair_rows = ["pair,metric,d,d_interp,U,p_raw,p_adj,significant"]
    pvals: list[float] = []
    pending: list[tuple[str, str, str, float, float, float]] = []
    for c1, c2 in combinations(CONDITIONS, 2):
        for name, _ in METRICS:
            x, y = data[c1][name], data[c2][name]
            if len(x) < 3 or len(y) < 3:
                continue
            d = cohens_d(x, y)
            try:
                res = mann_whitney_u(x, y)
                p = float(res["p_value"])
            except Exception:
                p = 1.0
            interp = (
                "negligible" if abs(d) < 0.2 else "small" if abs(d) < 0.5 else "medium" if abs(d) < 0.8 else "large"
            )
            pending.append((f"{c1}vs{c2}", name, interp, d, float("nan"), p))
            pvals.append(p)

    if pvals:
        adj, rejected = benjamini_hochberg(pvals, alpha=0.05)
        for (pair, name, interp, d, _u, p_raw), p_adj, rej in zip(pending, adj, rejected):
            pair_rows.append(f"{pair},{name},{d:+.3f},{interp},,{p_raw:.4f},{p_adj:.4f},{rej}")
    (OUT_DIR / "pairwise_effects.csv").write_text("\n".join(pair_rows) + "\n")

    # ── Markdown report ──────────────────────────────────────────────────
    md = ["# Bootstrap CI + Effect Size Report\n"]
    md.append("Generated by `scripts/bootstrap_ci_report.py` from `experiments/mx_{A,B,D}_s*`.\n")
    md.append("## Per-condition (mean [95% bootstrap CI])\n")
    md.append("| Condition | Metric | n | Mean | 95% CI |")
    md.append("|---|---|---|---|---|")
    for cond in CONDITIONS:
        for name, _ in METRICS:
            vals = data[cond][name]
            if not vals:
                continue
            mean = float(np.mean(vals))
            if len(vals) >= 3:
                _, lo, hi = bootstrap_ci(vals, n_bootstrap=5000, confidence=0.95, random_state=42)
                ci_str = f"[{lo:.3f}, {hi:.3f}]"
            else:
                ci_str = "(n<3)"
            md.append(f"| {cond} | {name} | {len(vals)} | {mean:.3f} | {ci_str} |")

    md.append("\n## Pairwise effect sizes (Cohen's d) + Mann-Whitney U (BH-adjusted)\n")
    md.append("| Pair | Metric | Cohen's d | Interpretation | p (raw) | p (BH-adj) | Sig (α=0.05) |")
    md.append("|---|---|---|---|---|---|---|")
    if pvals:
        for (pair, name, interp, d, _u, p_raw), p_adj, rej in zip(pending, adj, rejected):
            md.append(
                f"| {pair} | {name} | {d:+.3f} | {interp} | {p_raw:.4f} | {p_adj:.4f} | {'**yes**' if rej else 'no'} |"
            )

    md.append("\n_Cohen's d magnitudes: <0.2 negligible, <0.5 small, <0.8 medium, ≥0.8 large._\n")
    (OUT_DIR / "bootstrap_ci_report.md").write_text("\n".join(md))

    print(f"Wrote {OUT_DIR}/bootstrap_ci.csv")
    print(f"Wrote {OUT_DIR}/pairwise_effects.csv")
    print(f"Wrote {OUT_DIR}/bootstrap_ci_report.md")


if __name__ == "__main__":
    main()
