#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")/.."
# reproduce_paper.sh
# One-command reproduction of the BGF paper results.
#
# Usage:
#   bash reproduce_paper.sh            # fast sanity check (CPU, ~5 min)
#   bash reproduce_paper.sh --full     # full paper run (CPU baselines, ~30 min)
#   bash reproduce_paper.sh --figures  # regenerate all figures from existing experiments
#
# GPU-dependent LLM experiments (--include-llm) are excluded from automatic
# reproduction; run them manually via the pipeline scripts listed at the bottom
# of this file.
#
# ── Figure / Table manifest ──────────────────────────────────────────────────
# Table 1  (Ablation ladder V0-V4)
#   Generated by: python scripts/run_full_pipeline.py
#   Output:       analysis/tables/ablation_results.csv
#
# Table 2  (Cross-model bias index)
#   Generated by: python scripts/run_cross_model.py
#   Output:       analysis/tables/cross_model_results.csv
#
# Table 3  (Statistical significance: Mann-Whitney, Cohen's d)
#   Generated by: python scripts/run_full_pipeline.py (--seeds flag)
#   Output:       analysis/tables/significance_tests.csv
#
# Table 4  (Cross-cultural Spearman ρ)
#   Generated by: python scripts/run_cross_cultural.py
#   Output:       analysis/tables/cross_cultural_correlation.csv
#
# Figure 1 (Cooperation rate trajectories, multi-seed CI)
#   Generated by: python scripts/plot_trajectories_full.py --seeds 5
#   Output:       analysis/figures/cooperation_trajectories.pdf
#
# Figure 2 (Gini coefficient trajectories)
#   Generated by: python scripts/plot_trajectories_full.py --seeds 5
#   Output:       analysis/figures/gini_trajectories.pdf
#
# Figure 3 (Cross-model bias comparison bar chart)
#   Generated by: python scripts/plot_cross_model_comparison.py
#   Output:       analysis/figures/cross_model_bias_comparison.pdf
#
# Figure 4 (Cross-cultural scatter: ESS trust vs simulated cooperation)
#   Generated by: python scripts/plot_cross_cultural_validation.py
#   Output:       analysis/figures/cross_cultural_validation.pdf
#
# Figure 5 (Phase transitions: cooperation collapse, Gini, topology, power law)
#   Generated by: python scripts/plot_phase_transitions.py
#   Output:       analysis/figures/phase_transitions.pdf
#
# ── GPU experiment pipelines (manual, require 16 GB VRAM) ───────────────────
# bash pipeline_phase_c.sh          # 100 agents, 100 rounds, LLM + RAG
# bash pipeline_cross_cultural.sh --include-llm   # cross-cultural LLM run
# bash pipeline_bad_apple.sh        # adversarial agent stress test
# bash pipeline_macro_shock.sh      # macro-economic shock (50% wealth hit)
# bash pipeline_topology.sh         # network topology sweep
# bash pipeline_phase_d.sh          # 500-agent large-scale run
# ────────────────────────────────────────────────────────────────────────────

set -euo pipefail

FULL=0
FIGURES_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --full)    FULL=1 ;;
        --figures) FIGURES_ONLY=1 ;;
    esac
done

echo "======================================================="
echo "  Behavioral Grounding Framework — Paper Reproduction"
echo "======================================================="
echo ""

# ── 1. Python version check ────────────────────────────────────────────────
REQUIRED_PYTHON="3.10"
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "[check] Python version: $PYTHON_VERSION (required >= $REQUIRED_PYTHON)"

python3 -c "
import sys
if (sys.version_info.major, sys.version_info.minor) < (3, 10):
    print('ERROR: Python >= 3.10 is required')
    sys.exit(1)
"

# ── 2. Check / create virtualenv ──────────────────────────────────────────
echo ""
echo "[env]   Checking virtual environment..."
if [[ -d venv ]]; then
    source venv/bin/activate
    echo "        Activated existing venv/."
else
    python3 -m venv venv
    source venv/bin/activate
    pip install --quiet --upgrade pip
    pip install --quiet -r requirements.txt
    echo "        Created venv/ and installed dependencies."
fi

# ── 3. Run test suite ─────────────────────────────────────────────────────
echo ""
echo "[test]  Running test suite..."
pytest tests/ -q --tb=short 2>&1 | tail -10
echo "        Tests passed."

if [[ $FIGURES_ONLY -eq 1 ]]; then
    echo ""
    echo "[fig]   Regenerating all figures from existing experiments..."
    python scripts/run_full_pipeline.py --plots-only
    python scripts/plot_trajectories_full.py --seeds 5 || true
    python scripts/plot_cross_model_comparison.py || true
    python scripts/plot_cross_cultural_validation.py || true
    python scripts/plot_phase_transitions.py || true
    python scripts/export_figures_hires.py || true
    echo ""
    echo "======================================================="
    echo "  Figures regenerated."
    echo "  Output: analysis/figures/"
    echo "======================================================="
    exit 0
fi

# ── 4. Run CPU-only simulation pipeline ──────────────────────────────────
echo ""
if [[ $FULL -eq 1 ]]; then
    echo "[sim]   Running FULL baseline pipeline (30 rounds, 100 agents, seeds 42,123,7)..."
    echo "        → Table 1, Figures 1-2"
    python scripts/run_full_pipeline.py \
        --rounds 30 \
        --agents 100 \
        --seeds 42,123,7
else
    echo "[sim]   Running FAST baseline pipeline (5 rounds, 20 agents, seeds 42,123,7)..."
    echo "        (Use --full for complete paper reproduction)"
    python scripts/run_full_pipeline.py \
        --rounds 5 \
        --agents 20 \
        --seeds 42,123,7
fi

# ── 5. Trust gradient validation (GPU-free) ──────────────────────────────
echo ""
echo "[val]   Running trust-gradient sub-population validation..."
echo "        → Table 3 (partial)"
python scripts/run_trust_gradient.py || echo "        Skipped — run after full LLM experiments."

# ── 6. Cross-cultural validation (CPU baselines) ─────────────────────────
echo ""
echo "[xcult] Running cross-cultural baseline validation..."
echo "        → Table 4"
python scripts/run_cross_cultural.py --policy random || \
    echo "        Skipped — run pipeline_cross_cultural.sh for LLM results."

# ── 7. Regenerate figures ─────────────────────────────────────────────────
echo ""
echo "[fig]   Regenerating figures..."
python scripts/run_full_pipeline.py --plots-only || true
python scripts/plot_trajectories_full.py --seeds 3 || true
python scripts/plot_phase_transitions.py || true
python scripts/export_figures_hires.py || true

echo ""
echo "=== Policy sweep (CPU demo) ==="
python scripts/run_policy_sweep.py --dry-run || true

# ── 8. BRM Proposition 3 analytic certificate ─────────────────────────────
# Emits the four Δ_j sub-component values that the paper §6.1 cites as the
# Proposition 3 weight-robustness certificate, written to
# analysis/tables/brm_sensitivity.json under the `certificate` key.
echo ""
echo "[brm]   Emitting BRM Proposition 3 analytic certificate..."
python analysis/brm_sensitivity.py --emit-certificate --n-samples 500 \
    --out-json analysis/tables/brm_sensitivity.json
test -f analysis/tables/brm_sensitivity.json || (
    echo "ERROR: brm_sensitivity.json not produced"; exit 1
)
echo "        Wrote analysis/tables/brm_sensitivity.json"

# ── 9. Extended paper-table regeneration (cited by §8.1 + Table 8 row H4) ─
# The four CSVs below are read by analyses cited in the main paper.
# reproduce_paper.sh previously omitted them; an external reviewer therefore
# could not regenerate Table 8 row H4 (modularity), the §8.1 matrix table,
# the §6.6 baselines comparison, or the §8.1 hypothesis forest plot from
# this script alone.

# 9a. §8.1 Table H4 — cooperation-graph Newman modularity for the 20 mx_*
# cells. Skipped silently if the cells aren't on disk (so the fast smoke
# mode of this script doesn't fail on a fresh checkout).
echo ""
echo "[mod]   Extracting §8.1 cooperation-graph modularity (H4)..."
if compgen -G "experiments/mx_A_s*" > /dev/null 2>&1; then
    python scripts/extract_modularity_from_cells.py \
        --out analysis/tables/network_modularity_8_1.csv
    test -f analysis/tables/network_modularity_8_1.csv || (
        echo "ERROR: network_modularity_8_1.csv not produced"; exit 1
    )
    echo "        Wrote analysis/tables/network_modularity_8_1.csv"
else
    echo "        Skipped — no mx_*_s* cells on disk (run §8.1 first)."
fi

# 9b. §8.1 cross-cell matrix CSV — re-aggregates the per-cell summaries that
# the §8.1 results table draws from. Emitted by scripts/run_experiment_matrix.py
# in --skip-existing mode (no re-execution).
echo ""
echo "[mtx]   Re-aggregating §8.1 experiment matrix CSV..."
if compgen -G "experiments/mx_A_s*" > /dev/null 2>&1; then
    python scripts/run_experiment_matrix.py --conditions A B \
        --seeds 1,2,3,4,5,6,7,8,9,10 --rounds 30 --agents 100 --skip-existing \
        --output-csv analysis/tables/experiment_matrix_results.csv 2>&1 | tail -5
    test -f analysis/tables/experiment_matrix_results.csv || (
        echo "ERROR: experiment_matrix_results.csv not produced"; exit 1
    )
    echo "        Wrote analysis/tables/experiment_matrix_results.csv"
else
    echo "        Skipped — no mx_*_s* cells on disk."
fi

# 9c. §6.0/§6.5 forest plot — generated by analysis/forest_plot.py if the
# canonical forest_plot.json is present.
echo ""
echo "[fp]    Regenerating §6.0 hypothesis forest plot..."
if [[ -f analysis/tables/forest_plot.json ]]; then
    python analysis/forest_plot.py 2>&1 | tail -3 || true
    test -f analysis/figures/forest_plot.png && \
        echo "        Wrote analysis/figures/forest_plot.png" || \
        echo "        forest_plot.py produced no PNG (non-fatal)."
else
    echo "        Skipped — analysis/tables/forest_plot.json not present."
fi

# 9d. analysis/tables/llm_vs_baselines.csv is emitted by run_full_pipeline.py
# (line ~466 in current revision); we verify presence here rather than
# regenerating to avoid a second full-pipeline run.
echo ""
echo "[base]  Checking analysis/tables/llm_vs_baselines.csv..."
if [[ -f analysis/tables/llm_vs_baselines.csv ]]; then
    echo "        Present (size: $(wc -c < analysis/tables/llm_vs_baselines.csv) bytes)"
else
    echo "        Missing — emitted by run_full_pipeline.py; re-run --full to populate."
fi

echo ""
echo "=== Zenodo metadata check ==="
python -c "import json; d=json.load(open('zenodo.json')); assert 'title' in d; print('zenodo.json OK')" || true

echo ""
echo "======================================================="
echo "  Reproduction complete."
echo ""
echo "  Figures:     analysis/figures/"
echo "  Tables:      analysis/tables/"
echo "  Experiments: experiments/"
echo ""
echo "  GPU experiments (LLM policy) must be run separately:"
echo "    bash pipeline_phase_c.sh"
echo "    bash pipeline_cross_cultural.sh --include-llm"
echo "======================================================="
